name: chattr_app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment: 
  sdk: ^3.9.0-333.2.beta

dependencies:
  flutter:
    sdk: flutter
  english_words: ^4.0.0
  provider: ^6.1.5
  crypto: ^3.0.3
<<<<<<< HEAD
  http: ^1.1.0
=======
  shared_preferences: ^2.2.2
>>>>>>> d1174c32fec6677e6c626324223a5d62b309ebe8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true